### ISSUE TITLE
Successful login with wrong password

### ISSUE THREAD

**Issue by Zachary-Masson** [C4GDevs/ARCON.js#5]
Hello, I noticed that when I try to connect an incorrect password, the connected event is triggered as usual, but the error event is not.

**Comment by Zachary-Masson** [comment]
PS: Of course it really can't connect but arcon.js considers it connected

**Comment by Zachary-Masson** [comment]
on closer inspection, I have the impression that the buffer doesn't return the same value as in the condition

client.ts
![image](https://github.com/user-attachments/assets/10d457d7-f17e-4a34-b014-fc70c21e667d)

Result
![image](https://github.com/user-attachments/assets/0964f273-9237-4214-ada2-9b0bff47f0fb)

**Comment by ewenjo** [comment]
Fixed in `6.0.7`.

Thanks for the issue!

**Comment by Zachary-Masson** [comment]
thank u
