### ISSUE TITLE
Timeout problem with wrong IP or port

### ISSUE THREAD

**Issue by Zachary-Masson** [C4GDevs/ARCON.js#7]
I've noticed that when you set the wrong ip or port, arcon.js doesn't indicate that it can't connect, with the “error” event, it doesn't trigger any event.

**Comment by ewenjo** [comment]
Login timeouts emit a `disconnected` event with the reason `Login timed out`. It's not currently considered an error as reconnects are common and gracefully handled.

**Comment by Zachary-Masson** [comment]
i see, thx u
